#!/usr/bin/env bash
set -euo pipefail

# Backup / restore the HTPC user's ~/.kodi over SSH so a clean OS reinstall
# does not lose Kodi settings, library DBs, sources, and add-ons.
#
# Standalone -- not part of htpc-install. Uses the same dev/.env host as
# sync.sh.
#
# Usage (from the development machine):
#   dev/kodi-config-migrate.sh backup [archive]
#   dev/kodi-config-migrate.sh restore <archive>
#
# Typical flow:
#   1. Before wiping the OS:  dev/kodi-config-migrate.sh backup
#   2. Reinstall CachyOS, run htpc-install, reboot into Kodi once if you want
#   3. Restore on top:        dev/kodi-config-migrate.sh restore path/to/archive
#
# By default Thumbnails and temp/ are omitted (regenerated by Kodi; keeps
# the archive small). Pass --full to include everything under ~/.kodi.

script_dir() {
    cd "$(dirname "${BASH_SOURCE[0]}")" && pwd
}

load_env() {
    local env_file="$1"
    if [[ -f "${env_file}" ]]; then
        # shellcheck source=/dev/null
        source "${env_file}"
    fi
}

require_host() {
    : "${HTPC_DEV_HOST:?Set HTPC_DEV_HOST in dev/.env or the environment, e.g. user@catchyos.local}"
}

log() {
    printf 'kodi-config-migrate: %s\n' "$*" >&2
}

die() {
    log "$*"
    exit 1
}

# Remote login user's home and .kodi path (HTPC_DEV_HOST is user@host).
remote_kodi_home() {
    ssh -o BatchMode=yes "${HTPC_DEV_HOST}" 'printf "%s/.kodi\n" "$HOME"'
}

pick_compressor() {
    if command -v zstd >/dev/null 2>&1; then
        printf 'zstd\n'
    elif command -v gzip >/dev/null 2>&1; then
        printf 'gzip\n'
    else
        die "Need zstd or gzip on this machine to create/read the archive."
    fi
}

archive_extension() {
    case "$1" in
        zstd) printf 'tar.zst\n' ;;
        gzip) printf 'tar.gz\n' ;;
        *)    die "Unknown compressor: $1" ;;
    esac
}

detect_archive_compressor() {
    local archive="$1"
    case "${archive}" in
        *.tar.zst|*.tzst) printf 'zstd\n' ;;
        *.tar.gz|*.tgz)   printf 'gzip\n' ;;
        *)
            die "Unrecognized archive type (use .tar.zst or .tar.gz): ${archive}"
            ;;
    esac
}

default_archive_path() {
    local compressor="$1" ext backups
    ext="$(archive_extension "${compressor}")"
    backups="$(script_dir)/backups"
    mkdir -p "${backups}"
    printf '%s/kodi-config-%s.%s\n' \
        "${backups}" "$(date +%Y%m%d-%H%M%S)" "${ext}"
}

# Stop Kodi / the HTPC Kodi session so files are not mid-write.
remote_stop_kodi() {
    log "Stopping Kodi on ${HTPC_DEV_HOST} (if running)."
    # Prefer the exclusive session unit; fall back to killing the user process.
    # shellcheck disable=SC2029 # intentional: remote shell runs the script body
    ssh -o BatchMode=yes "${HTPC_DEV_HOST}" bash -s <<'EOF'
set +e
if command -v systemctl >/dev/null 2>&1; then
    sudo -n systemctl stop htpc-kodi.service 2>/dev/null \
        || systemctl stop htpc-kodi.service 2>/dev/null \
        || true
fi
pkill -u "$(id -u)" -x kodi.bin 2>/dev/null || true
pkill -u "$(id -u)" -x kodi 2>/dev/null || true
sleep 1
EOF
}

tar_exclude_args() {
    local full="$1"
    if [[ "${full}" == true ]]; then
        return 0
    fi
    # Regenerated by Kodi; omit to keep archives small.
    printf '%s\0' \
        --exclude=temp \
        --exclude=userdata/Thumbnails \
        --exclude=*.log
}

cmd_backup() {
    local full="$1"
    local archive="${2:-}"
    local compressor kodi_home
    local -a remote_tar

    require_host
    compressor="$(pick_compressor)"
    if [[ -z "${archive}" ]]; then
        archive="$(default_archive_path "${compressor}")"
    fi
    mkdir -p "$(dirname "${archive}")"

    kodi_home="$(remote_kodi_home)"
    log "Remote Kodi home: ${kodi_home}"

    if ! ssh -o BatchMode=yes "${HTPC_DEV_HOST}" "test -d $(printf '%q' "${kodi_home}")"; then
        die "No Kodi home at ${HTPC_DEV_HOST}:${kodi_home}"
    fi

    remote_stop_kodi

    remote_tar=(tar -C "${kodi_home}" -cf -)
    if [[ "${full}" != true ]]; then
        remote_tar+=(--exclude=temp --exclude=userdata/Thumbnails --exclude='*.log')
    fi
    remote_tar+=(.)

    log "Creating ${archive} from ${HTPC_DEV_HOST}:${kodi_home}"
    # Stream a tar of the .kodi directory contents (so restore unpacks into
    # ~/.kodi/... rather than nesting an extra .kodi/).
    ssh -o BatchMode=yes "${HTPC_DEV_HOST}" "$(printf '%q ' "${remote_tar[@]}")" \
        | case "${compressor}" in
              zstd) zstd -T0 -q -o "${archive}" ;;
              gzip) gzip -c > "${archive}" ;;
          esac

    log "Backup complete: ${archive} ($(du -h "${archive}" | awk '{print $1}'))"
    if [[ "${full}" != true ]]; then
        log "Excluded temp/ and userdata/Thumbnails (pass --full to include)."
    fi
}

cmd_restore() {
    local archive="$1"
    local compressor kodi_home remote_tmp stamp

    require_host
    [[ -n "${archive}" ]] || die "Usage: $(basename "$0") restore <archive>"
    [[ -f "${archive}" ]] || die "Archive not found: ${archive}"

    compressor="$(detect_archive_compressor "${archive}")"
    case "${compressor}" in
        zstd) command -v zstd >/dev/null 2>&1 || die "zstd required to read ${archive}" ;;
        gzip) command -v gzip >/dev/null 2>&1 || die "gzip required to read ${archive}" ;;
    esac

    kodi_home="$(remote_kodi_home)"
    stamp="$(date +%Y%m%d-%H%M%S)"
    remote_tmp="/tmp/kodi-config-restore-${stamp}.tar"

    remote_stop_kodi

    log "Uploading archive to ${HTPC_DEV_HOST}:${remote_tmp}"
    case "${compressor}" in
        zstd) zstd -dc "${archive}" | ssh -o BatchMode=yes "${HTPC_DEV_HOST}" "cat > '${remote_tmp}'" ;;
        gzip) gzip -dc "${archive}" | ssh -o BatchMode=yes "${HTPC_DEV_HOST}" "cat > '${remote_tmp}'" ;;
    esac

    log "Restoring into ${HTPC_DEV_HOST}:${kodi_home}"
    # shellcheck disable=SC2029
    ssh -o BatchMode=yes "${HTPC_DEV_HOST}" bash -s <<EOF
set -euo pipefail
kodi_home="${kodi_home}"
remote_tmp="${remote_tmp}"
stamp="${stamp}"

if [[ -e "\${kodi_home}" ]]; then
    backup="\${kodi_home}.pre-restore-\${stamp}"
    echo "kodi-config-migrate: moving existing \${kodi_home} -> \${backup}" >&2
    mv "\${kodi_home}" "\${backup}"
fi

mkdir -p "\${kodi_home}"
tar -C "\${kodi_home}" -xf "\${remote_tmp}"
rm -f "\${remote_tmp}"
# Ensure ownership matches the login user (tarball may have been made as same user).
chown -R "\$(id -u):\$(id -g)" "\${kodi_home}"
echo "kodi-config-migrate: restore complete at \${kodi_home}" >&2
EOF

    log "Done. Start the Kodi session (e.g. htpc-switch kodi) to verify."
    log "Run restore after htpc-install so your userdata wins over seeded defaults."
}

usage() {
    cat >&2 <<EOF
Usage: $(basename "$0") [--full] backup [archive]
       $(basename "$0") restore <archive>

  backup   Pull ~/.kodi from the HTPC into a local archive.
  restore  Push an archive back onto the HTPC's ~/.kodi.

Options:
  --full   Include Thumbnails and temp/ (default: omit; Kodi regenerates them).

Uses HTPC_DEV_HOST from dev/.env (same as sync.sh).
EOF
}

main() {
    local script_directory full=false
    script_directory="$(script_dir)"
    load_env "${script_directory}/.env"

    while [[ "${1:-}" == --* ]]; do
        case "$1" in
            --full) full=true; shift ;;
            -h|--help) usage; exit 0 ;;
            *) die "Unknown option: $1" ;;
        esac
    done

    local command="${1:-}"
    shift || true

    case "${command}" in
        backup)
            cmd_backup "${full}" "${1:-}"
            ;;
        restore)
            [[ "${full}" == false ]] || die "--full only applies to backup."
            cmd_restore "${1:-}"
            ;;
        *)
            usage
            exit 1
            ;;
    esac
}

main "$@"
